##################################################################
#                           _        _____                _ _    #
#      /\        /\        | |      / ____|              | | |   #
#     /  \      /  \  _   _| |_ ___| (___  _ __ ___   ___| | |_  #
#    / /\ \    / /\ \| | | | __/ _ \\___ \| '_ ` _ \ / _ \ | __| #
#   / ____ \  / ____ \ |_| | || (_) |___) | | | | | |  __/ | |_  #
#  /_/    \_\/_/    \_\__,_|\__\___/_____/|_| |_| |_|\___|_|\__| #
#                                                                #
# Version: 2.5.3                                                 #
# Author: Pulsi_                                                 #
# Thanks for using this plugin!                                  #
#                                                                #
##################################################################

#Receive updates messages when there is a new Update available
update-checker: true


######################################################
#                   < AUTOSMELT >                    #
######################################################
AutoSmelt:

  #Disable the autosmelt in creative mode, this will avoid the possibility of dupe blocks
  disable-creative-mode: true

  #Automatically smelt Iron Ore -> Permission: advancedautosmelt.smelt.iron
  smelt-iron: true
  #Give or not the experience when breaking an Iron Ore Block
  give-exp-iron: true
  #Give to the Player some Experience for Mining Iron Ores
  iron-exp: 1

  ##Automatically smelt Gold Ore -> Permission: advancedautosmelt.smelt.gold
  smelt-gold: true
  #Give or not the experience when breaking an Iron Ore Block
  give-exp_gold: true
  #Give to the Player some Experience for Mining Gold Ores
  gold-exp: 2

  #The stone will be mined like silk touch -> advancedautosmelt.smelt.stone
  smelt-stone: true

  #This will smelt ores not smelted in the Inventory
  smelt-ores-in-inventory: true


######################################################
#                   < AUTOPICKUP >                   #
######################################################
AutoPickup:

  #Should the plugin enable this Option? -> Permission: advancedautosmelt.pickup
  enable-autopickup: true

  #The player will directly receive Experience -> Permission: advancedautosmelt.pickupexp
  autopickup-experience: true

  #The list where autopickup won't work
  use-blacklist: false
  blacklist:
    - SAND
    - DIRT


######################################################
#                    < FORTUNE >                     #
######################################################

Fortune: #Please, if you run into some problems like Fortune section not save parts, this is not a bug! Reload the server for make these saves work!

  #Enable the fortune feature, this will give extra blocks based on your fortune level -> Permission: advancedautosmelt.fortune
  enable-fortune-support: true

  #Use the block whitelist
  use-whitelist: true
  #This will work with blocks too
  whitelist:
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - REDSTONE_ORE