##################################################################
#                           _        _____                _ _    #
#      /\        /\        | |      / ____|              | | |   #
#     /  \      /  \  _   _| |_ ___| (___  _ __ ___   ___| | |_  #
#    / /\ \    / /\ \| | | | __/ _ \\___ \| '_ ` _ \ / _ \ | __| #
#   / ____ \  / ____ \ |_| | || (_) |___) | | | | | |  __/ | |_  #
#  /_/    \_\/_/    \_\__,_|\__\___/_____/|_| |_| |_|\___|_|\__| #
#                                                                #
# Version: 2.7.2                                                 #
# Author: Pulsi_                                                 #
# Thanks for using this plugin!                                  #
#                                                                #
##################################################################

#Receive updates messages when there is a new Update available
update-checker: true

#If your server is on 1.13 or more, you should put this option on false
enable-legacy-support: true

######################################################
#                   < AUTOSMELT >                    #
######################################################
AutoSmelt:

  #Disable the autosmelt in creative mode, this will avoid the possibility of dupe blocks
  disable-creative-mode: true

  #Automatically smelt Iron Ore -> Permission: advancedautosmelt.smelt.iron
  smelt-iron: true
  #Give or not the experience when breaking an Iron Ore Block
  give-exp-iron: true
  #Give to the Player some Experience for Mining Iron Ores
  iron-exp: 1

  #Automatically smelt Gold Ore -> Permission: advancedautosmelt.smelt.gold
  smelt-gold: true
  #Give or not the experience when breaking an Iron Ore Block
  give-exp_gold: true
  #Give to the Player some Experience for Mining Gold Ores
  gold-exp: 2

  #The stone will be mined like silk touch -> advancedautosmelt.smelt.stone
  smelt-stone: true

  #Instead of give Obsidian, it will give the EnderChest when broken
  smelt-enderchest: true

  #This will smelt ores not smelted in the Inventory
  smelt-ores-in-inventory: true
  inv-smelt:
    #Smelt Iron Ores in the Inventory
    iron-ore: true

    #Smelt Gold Ores in the Inventory
    gold-ore: true

    #Smelt Cobblestone in the Inventory
    cobblestone: true


######################################################
#                   < AUTOPICKUP >                   #
######################################################
AutoPickup:

  #Should the plugin enable this Option? -> Permission: advancedautosmelt.pickup
  enable-autopickup: true

  #The player will directly receive Experience -> Permission: advancedautosmelt.pickupexp
  autopickup-experience: true

  #The list where autopickup won't work
  use-blacklist: false
  blacklist:
    - SAND
    - DIRT


######################################################
#                    < FORTUNE >                     #
######################################################

Fortune: #Please, if you run into some problems like Fortune section not save parts, this is not a bug! Reload the server for make these saves work!

  #Enable the fortune feature, this will give extra blocks based on your fortune level -> Permission: advancedautosmelt.fortune
  enable-fortune-support: true

  #Use the block whitelist
  use-whitelist: true
  #This will work with blocks too
  whitelist:
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - REDSTONE_ORE


######################################################
#                   < BLACKLIST >                    #
######################################################
Disabled-Worlds:
  - example1
  - example2


#######################################################
#                  < MESSAGES PART >                  #
#######################################################

reload-message: "&8&l<&d&lAdvanced&a&lAuto&c&lSmelt&8&l> &aPlugin reloaded!"

no-permission-message: "&8&l<&d&lAdvanced&a&lAuto&c&lSmelt&8&l> &cYou don't have the permission!"

unknown-command: "&8&l<&d&lAdvanced&a&lAuto&c&lSmelt&8&l> &cUnknown Command!"

toggled-on-message: "&8&l<&d&lAdvanced&a&lAuto&c&lSmelt&8&l> &7Your %toggled_ability% has been toggled &2On&7!"

toggled-off-message: "&8&l<&d&lAdvanced&a&lAuto&c&lSmelt&8&l> &7Your %toggled_ability% has been toggled &cOff&7!"